### PR TITLE
Remove gRPC server address

### PR DESCRIPTION
**Pull request by arunkumarchacko**

### CODE REVIEW

**Review by Deependra-Patel — COMMENTED** [review]
Wouldn't it be a breaking change if some customer is already using this property?

**Comment by Deependra-Patel** [comment]
Let's add context why are we removing it

**Comment by arunkumarchacko** [comment]
> Wouldn't it be a breaking change if some customer is already using this property?

This will not break any customer since this config is not getting used.
Also, this is not a documented configuration

**Review by Deependra-Patel — APPROVED** [review]

**Pull request merged**
