### PR TITLE
Add generated preprod client for GCS

### PR DESCRIPTION
**Pull request by mprashanthsagar**

### CODE REVIEW

**Review by medb — CHANGES_REQUESTED** [review]
How this client was generated? Usually Maven build should be configured to generate this code during build instead of directly committing it to the repo.

**Comment by mprashanthsagar** [comment]
> How this client was generated? Usually Maven build should be configured to generate this code during build instead of directly committing it to the repo.

This client was generated from https://github.com/google/apis-client-generator (from GCS team) based on the api config for Directory apis, the config isn't published to production yet.

**Comment by medb** [comment]
> This client was generated from https://github.com/google/apis-client-generator (from GCS team) based on the api config for Directory apis, the config isn't published to production yet.

I think that the right approach will be to integrate running this script in generate sources phase of the Maven build: https://maven.apache.org/guides/mini/guide-generating-sources.html

**Comment by mprashanthsagar** [comment]
> > This client was generated from https://github.com/google/apis-client-generator (from GCS team) based on the api config for Directory apis, the config isn't published to production yet.
> 
> I think that the right approach will be to integrate this script in Maven build and run it during `generate-sources` phase of the Maven build: https://maven.apache.org/guides/mini/guide-generating-sources.html


The code generator requires python 2.7 and `pip install requirements` to even build the generator. I don't think it is feasible to  integrate into the maven generate sources phase. It is a one time setup (temporary) till APIs get published, which would unblock us on development

**Review by Deependra-Patel — APPROVED** [review]

**Pull request merged**
