### PR TITLE
Fix: prevent clobbering of SSL trustCertificates

### PR DESCRIPTION
**Pull request by Deependra-Patel**
Related to #782

### CODE REVIEW

**Comment by Deependra-Patel** [comment]
cc: @frankyn

**Review by medb — APPROVED** [review]
Should we cherry-pick merged PRs in 2.1.x branch too?

**Comment by Deependra-Patel** [comment]
> Should we cherry-pick commit [5635728](https://github.com/GoogleCloudDataproc/hadoop-connectors/commit/56357281701f2ede1fba2bd8e9b6f248f06c1e13) for merged PR #782 in 2.1.x branch too?

@medb Sorry didn't understand the comment. This PR (#784) is indeed for branch-2.1.x.
#786 is for branch 2.2.x
#782 is for master

**Pull request merged**
