### PR TITLE
IO Statistics keys tracking implementation

### PR DESCRIPTION
**Pull request by muthugit**

### CODE REVIEW

**Review by medb — CHANGES_REQUESTED** [review]
This PR is quite big, can we split it in multiple parts? For example, is it possible to send PR that adds support for only low-level HTTP API IO Statistics, like this: https://github.com/apache/hadoop/blob/832a3c6a8918c73fa85518d5223df65b48f706e9/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/statistics/StoreStatisticNames.java#L320-L354

**Comment by muthugit** [comment]
@googlebot I fixed it.

**Comment by muthugit** [comment]
@googlebot I fixed it.

**Comment by muthugit** [comment]
@googlebot I fixed it.

**Comment by muthugit** [comment]
Split this PR and tracked HTTP related keys in https://github.com/GoogleCloudDataproc/hadoop-connectors/pull/608
Closing this PR.

Ref: https://github.com/GoogleCloudDataproc/hadoop-connectors/pull/607#pullrequestreview-745681280

**Pull request closed without merging**
