### PR TITLE
Prevent on using dot in a bucket name when running integration tests

### PR DESCRIPTION
**Pull request by majdyz**
This small PR is removing the occurrence of . ("dot") character in the system username for generating the bucket name when running the integration test. 

To reproduce the error:
Set the `user.name` property with any username that has dot character in it, and run the integration tests.

### CODE REVIEW

**Comment by majdyz** [comment]
@googlebot I signed it!

**Comment by jaceklaskowski** [comment]
LGTM

**Review by medb — APPROVED** [review]

**Comment by medb** [comment]
Thank you for the fix!

**Pull request merged**
